// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_ZXMoINlQKYfp9QFLP3DsW0TkT6F5ZwY',
    appId: '1:68462150954:web:fe129b6244268e48faca53',
    messagingSenderId: '68462150954',
    projectId: 'paletti-ee8dc',
    authDomain: 'paletti-ee8dc.firebaseapp.com',
    storageBucket: 'paletti-ee8dc.appspot.com',
    measurementId: 'G-08ML3MJ0P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCzQS4zOtDb-z3OzEEGAnypTR4BTMVIMU',
    appId: '1:68462150954:android:eaa3d198d808425afaca53',
    messagingSenderId: '68462150954',
    projectId: 'paletti-ee8dc',
    storageBucket: 'paletti-ee8dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmTdGn0JMyx6HxDNHABDoRJsJ9hWShTWQ',
    appId: '1:68462150954:ios:f6a80a771310353bfaca53',
    messagingSenderId: '68462150954',
    projectId: 'paletti-ee8dc',
    storageBucket: 'paletti-ee8dc.appspot.com',
    iosClientId: '68462150954-4c2o7v8faf8q4abm4asmsu9ngjq97ufd.apps.googleusercontent.com',
    iosBundleId: 'com.example.paletti1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmTdGn0JMyx6HxDNHABDoRJsJ9hWShTWQ',
    appId: '1:68462150954:ios:f6a80a771310353bfaca53',
    messagingSenderId: '68462150954',
    projectId: 'paletti-ee8dc',
    storageBucket: 'paletti-ee8dc.appspot.com',
    iosClientId: '68462150954-4c2o7v8faf8q4abm4asmsu9ngjq97ufd.apps.googleusercontent.com',
    iosBundleId: 'com.example.paletti1',
  );
}
